### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bangarharshit** [saulmm/Material-Movies#24]
Can you please add a license to this project?

**Comment by jobrightpeter** [comment]
+1

**Comment by pjobright** [comment]
+1

**Comment by saulmm** [comment]
All done! Thank you!

**Comment by pjobright** [comment]
@saulmm Thank you very much for this. This project is amazing and is exactly what I had been looking for.

**Comment by saulmm** [comment]
@pjobright, glad to help!
