### ISSUE TITLE
Presenter interfaces 

### ISSUE THREAD

**Issue by pedrovgs** [saulmm/Material-Movies#4]
Hi!!!

I see you have some presenters declared as a class and as an interface when you only have one implementation. I don't see any factory or other creational pattern to decouple the interface and the implementation, just a new XPrensenterImpl inside your activity. Don't you think you don't need the interfaces for `MovieDetailPresenterImpl` and `PopularShowsPresenterImpl`?

**Comment by saulmm** [comment]
Yep @pedrovgs thank you :) 

I have deleted both interfaces and created an abstract class to handle life cycle events called `Presenter`

`Presenter.java`

``` java

/**
 * @author Saul M.
 */
package com.hackvg.android.mvp.presenters;

/**
 * Interface that represents a Presenter in the model view presenter Pattern
 * defines methods to manage the Activity / Fragment lifecycle
 */
public abstract class Presenter {

    /**
     * Called when the presenter is initialized
     */
    public abstract void start ();

    /**
     * Called when the presenter is stop, i.e when an activity
     * or a fragment finishes
     */
    public abstract void stop ();
}
```

`MoviesPresenter.java`

``` java
public class MoviesPresenter extends Presenter {
...
```

`MovieDetailPresenter.java`

``` java
public class MovieDetailPresenter extends Presenter {
...
```

**Comment by pedrovgs** [comment]
hahaha you don't have to change your code @saulmm. I just want to know your opinion! Anyway, thanks for your change!

**Comment by saulmm** [comment]
I've realized that you were right, so I have corrected, the interfaces of the presenters are unnecessary if have only one implementation, thus,  to have two files that make no sense :+1:
