### ISSUE TITLE
Bus usage

### ISSUE THREAD

**Issue by pedrovgs** [saulmm/Material-Movies#5]
Reading your code and the part of the article where you talk about the Otto usage to communicate your different modules I see two points I'd like to discuss with you:

The first one is related to `BusProvider`. This class is a really cool idea to hide the buses when you are going to choose to post a message or register to listen messages and to keep the buses inside a static attribute. This class is something like a "Factory" but I see something weird. You have been working really hard to decouple your implementations details but you are returning `com.squareup.otto.Bus` instances in this class. Don't you thing you are coupling all your layers to the same Bus implementation when the objective of all your code is just the opposite one?

The second question is related with the `Bus` philosophy. With the current implementation based on different layers and the usage of a bus I can post an event directly to any other module just doing something like:

``` java

Bus modelBus = BusProvider.getRestBusInstance();
modelBus.post(new AnyEvent());

```

Don't you think this is a little bit dangerous backdoor in your code? If someone is listening I can jump from one place of my code to other and create a collateral effect without any restrictions. Don't you prefer to do your dependencies explicit and invoke methods instead of post an event into the bus? I also use this library for some of my projects and I think Otto is a really powerful tool to notify global events and create plugins around this concept, for example to notify when your have received a new push notification.

Thanks again for your time and publish this code!!!

**Comment by saulmm** [comment]
Hi @pedrovgs 

Regarding the first question, I do not understand exactly what you mean with : 

`Don't you thing you are coupling all your layers to the same Bus implementation when the objective of all your code is just the opposite one?`

The module `:domain` and the module `:model` have the module `:common` as dependency, in that module is  where the provider of the buses is implemented, in what way I am coupling the modules with this implementation?

Regarding the second question, I liked the approach that has you given it, I had not thought of that, however, I would like to study RXJava and see if it fits the needs of the project, what do you think?

Thank you for your issue :smile:

**Comment by pedrovgs** [comment]
What I mean when I talk about your coupling to the Bus is not related with your modules configuration, it is related to the library you are using. You are using an instance of the Bus declared inside Square's library without hide it or wrap it, and by default, coupling all your code to that Bus implementation. This usage of the Bus seems weird when you are so worried about decouple your system in the blog post you've written.

Related to RxJava, the usage of that library (almost a framework) will change how you work with all your code and will condition all your design. RxJava is not just execute code out of the UI thread easily, it's related to how you model your software to resolve your problem thinking in your data as streams of data. If you are going to use RxJava, and you want to use it well and get all the possible benefit you'll have to change your architecture. Observability is one of the keys of Reactive and I'm not really sure if you need that level of observability to implement your app.

**Comment by mhdatie** [comment]
I'm with @pedrovgs when it comes to changing architectures. RxJava acts like a pipeline to your data. Instead of having nested callbacks on success with retrofit or using Otto bus to send the event and then calling another API method, RxJava will observe the data you receive from the API, if (success), you send the data to your next call, if not, somewhere else, and so on. It's not so easy to master RxJava, but the application logic becomes easier to build if it was predefined. 

One good use of RxJava is when you have a download queue, and you are waiting for, let's say, 5 download jobs to be completed, and then start with another 5. I have seen this in this repo which has the MVP pattern: https://github.com/jparkie/Aizoban

**Comment by saulmm** [comment]
I am working to bring RX to the project & replace all the bus usage

**Comment by amouly** [comment]
@saulmm cool, i'm waiting to see that!
