### ISSUE TITLE
MoviesPresenter class missing?

### ISSUE THREAD

**Issue by jskierbi** [saulmm/Material-Movies#7]
Hi, I don't see MoviesPresenter class, and unfortunately project won't compile

I've managed to recreate it using commits history - there was a change where you moved multiple interfaces + impl to single abstract Presenter base class, but unfortunately movies won't load at all.

Please check this -> maybe fresh clone and check what's what :)

**Comment by saulmm** [comment]
Yep, a problem with git -> [MoviesPresenter](https://github.com/saulmm/Material-Movies/blob/master/HackVG/app/src/main/java/com/hackvg/android/mvp/presenters/MoviesPresenter.java)
